
name: Deploy to Amazon ECR image

on:
  push:
    branches: [ "main" ]
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TF_AWS_LAB_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_AWS_LAB_KEY }}
  AWS_REGION: us-east-1
  directory: 01-tfstate
  directory-repo: 02-repo                  
  directory: 03-image/app
  repo_name: lab_challenge
  image_name: app
  tag_name: v0.1


permissions:
  contents: read

jobs:
  configpipeline:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

  deploystate:
      name: deploy state
      runs-on: ubuntu-latest
      environment: production
      steps:
        - name: Checkout
          uses: actions/checkout@v4 
        
        - name: deployimage
          run: |      
           terraform init -reconfigure
           terraform plan -lock=false
           terraform apply -auto-approve -lock=false

              
  deployrepo:
     name: deploy repo
     runs-on: ubuntu-latest
     environment: production
     steps:
       - name: Checkout
         uses: actions/checkout@v4 
       
       - name: deployimage
         run: | 
